Vagrant.configure("2") do |config|
  config.vm.box = "alvistack/ubuntu-24.04"
  config.vm.box_version = "20250202.1.1"
      
  # Define um IP fixo
  config.vm.network "private_network", ip: "192.168.56.10"

  # Redireciona a porta 80 (HTTP) da VM para a 8080 no host
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Configuração do VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  # Provisionamento via Shell Script
end
